### PR TITLE
add dashboard overview [#160261250]

### PR DESCRIPTION
**Pull request by robertjsullivan**
Signed-off-by: Robert Sullivan <rsullivan@pivotal.io>

### CODE REVIEW

**Comment by kbakas-piv** [comment]
@robertjsullivan can you update with a screenshot of new dashboard?

**Comment by rheaton** [comment]
screen shot 2018-10-15 at 11 15 18 am
screen shot 2018-10-15 at 11 15 41 am


@kbakas-piv @pspinrad Here are a couple screenshots, where is the appropriate place to put them in the docs? Also, we thought it might be cool to see _one_ red box, so we've uploaded both. What do you think, Katrina?

**Comment by rheaton** [comment]
screen shot 2018-10-15 at 11 18 06 am


Screenshot where it says "Example Company Production" rather than "acceptance-v1-4" (acceptance-v1-4 is probably fine for docs purposes tho...)

**Comment by kbakas-piv** [comment]
@pspinrad can you add in screenshots as you see appropriate please?

**Comment by pspinrad** [comment]
Thanks @robertjsullivan @rheaton @kbakas-piv !

**Pull request merged**
