### PR TITLE
Add documentation for new threshold type

### PR DESCRIPTION
**Pull request by rheaton**
https://www.pivotaltracker.com/story/show/161137153

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks @rheaton !

**Comment by pspinrad** [comment]
New comparison operator makes sense-- but for those yes/no tests "Can X do Y?" -- looking at it more, think it would be simpler to keep the `Equals 1/TRUE` rather than change to `Inequals 0/FALSE` -- assuming they're logically the same @rheaton

**Comment by rheaton** [comment]
They are not the same logically. The equality alert will go off whenever the value is _not_ equal so the behavior is actually changing in 1.4. 

Essentially, there are 3 possible values for this: `-1`, `0`, `1` and we _only_ want the alert to go off for `0` and `-1` is a "no data" scenario and we already have alerts that would go off.

**Comment by pspinrad** [comment]
@rheaton Oh, good to know, thanks!  I thought it was boolean, but actually it's more heisenbergian!

**Pull request merged**
