### PR TITLE
Add docs for new SVM free chunks of disk

### PR DESCRIPTION
**Pull request by rheaton**
- Update HAPI documentation
- Add SVM for free chunks and description

Signed-off-by: Rachel Heaton <rheaton@pivotal.io>

### CODE REVIEW

**Comment by rheaton** [comment]
Amber is out this week so we don't need her to review.

**Comment by mlimonczenko** [comment]
Thanks, @rheaton. Will take a look.

**Comment by mlimonczenko** [comment]
@kbakas-piv We took a look and made a few changes. 
We'll hold off on merging until we get the okay from you

**Comment by kbakas-piv** [comment]
I was just able to review them. Please go ahead and merge @mlimonczenko

**Pull request merged**
