### PR TITLE
Docs overhaul

### PR DESCRIPTION
**Pull request by johncornish**
Typos, punctuation, snippets, sentence structure, spacing, consistency of enclosing quotes in some instances

### CODE REVIEW

**Comment by johncornish** [comment]
My changes don't quite conform to the style guide--could we hold off on accepting this PR until I get some flex hour time these next few days to do an overhaul to the overhaul?

**Comment by cshollingsworth** [comment]
Hi, @johncornish ! I'd be happy to pair with you tomorrow or next week on overhaul part two, if you'd like. Feel free to ping me on Slack and let me know.

**Comment by johncornish** [comment]
Shoot, thought I had resolved the conflicts by rebasing

**Comment by johncornish** [comment]
@JacobLNewton any objections to merging this? It's starting to get stale as we complete other docs stories

**Pull request merged**
