### PR TITLE
Update release docs for healthwatch v1.4.5 [#163829027]

### PR DESCRIPTION
**Pull request by farmermel**
Update release docs for healthwatch v1.4.5

### CODE REVIEW

**Comment by farmermel** [comment]
The force push was from amending a commit for spelling! It was force-push-with-lease.

**Comment by ljarzynski** [comment]
@kbakas-piv By couple do you mean like listing out the features first and then the bug fixes? It looks like that's what we do for OM and PAS: https://docs.pivotal.io/pivotalcf/2-4/pcf-release-notes/opsmanager-rn.html#2-4-4 and https://docs.pivotal.io/pivotalcf/2-4/pcf-release-notes/runtime-rn.html#2.4.2

**Comment by jncd** [comment]
(@ljarzynski) And in the new [release note template](https://docs-wiki.cfapps.io/wiki/style/release-notes.html) we break up the list into "features" and "resolved issues".

**Comment by ljarzynski** [comment]
@jncd Thanks for letting me know!

**Pull request merged**
