### PR TITLE
1.6.1 release notes

### PR DESCRIPTION
**Pull request by iplay88keys**
** Please don't merge until 1.6.0 is out**

### CODE REVIEW

**Comment by iplay88keys** [comment]
** Please don't merge until 1.6.0 is out**

**Comment by mlimonczenko** [comment]
Thanks, @iplay88keys! Feel free to slack us when this is ready to go.

**Comment by hillrw3** [comment]
Hi all, this is ready to be merged.

**Comment by paigecalvert** [comment]
Thank you!

**Pull request merged**
