### PR TITLE
add uaac cli help section [#153909528]

### PR DESCRIPTION
**Pull request by robertjsullivan**
Signed-off-by: Rob Hill <rhill@pivotal.io>

### CODE REVIEW

**Comment by scribblingfox** [comment]
Thank you kindly, @robertjsullivan!

**Comment by AmberAlston** [comment]
Thanks all! FYI that this happened @vikafed

**Comment by AmberAlston** [comment]
FYI @jbayer this addresses some of your previous Healthwatch docs feedback

**Comment by jbayer** [comment]
thanks @AmberAlston this looks good!

**Pull request merged**
