### PR TITLE
Update release-notes.html.md.erb

### PR DESCRIPTION
**Pull request by kbakas-piv**
Edited the ordering of the dependency updates to be alphabetical

### CODE REVIEW

**Comment by originalhat** [comment]
We approve.

**Comment by mlimonczenko** [comment]
Thanks, @kbakas-piv!

**Comment by mlimonczenko** [comment]
Looks like the release notes have been reworked since this PR has been made. Mind taking a look at it again, @kbakas-piv?

**Comment by ljarzynski** [comment]
Noticed the story branch was already merged into 1.5, so we applied a commit directly to 1.5 to flip the order of the dependencies: https://github.com/pivotal-cf/docs-pcf-healthwatch/commit/f9840459d7fe3e22fd2f14710164affe66c5891a.

**Pull request closed without merging**
