### PR TITLE
replace loader.dropped content with ingestor.dropped [#155996794]

### PR DESCRIPTION
**Pull request by majidmade**
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

### CODE REVIEW

**Comment by AmberAlston** [comment]
DO NOT MERGE. Story is rejected

**Comment by ljarzynski** [comment]
@AmberAlston 10-4. Blocking story until we hear different.

**Comment by AmberAlston** [comment]
@ljarzynski Thanks! Acceptance of https://www.pivotaltracker.com/story/show/155996794 is what can unblock this merge. @kbakas-piv and I can also merge upon acceptance.

**Comment by kbakas-piv** [comment]
Looks good to me. Merging and unblocking, will accept story @ljarzynski

**Pull request merged**
