### PR TITLE
Add known issue for Redis Worker Scaling property

### PR DESCRIPTION
**Pull request by oppegard**
[#168005525]

Signed-off-by: Glenn Oppegard <goppegard@pivotal.io>

### CODE REVIEW

**Comment by mlimonczenko** [comment]
Thank you, @oppegard. Made slight changes and approved.

**Comment by oppegard** [comment]
@kbakas it will be fixed in HW 1.6.3, which wasn't ready for release when this PR was created a month ago. Should I update this PR to reference 1.6.3?

**Comment by kbakas** [comment]
Yes please

**Comment by mklanjsek** [comment]
@kbakas, Glenn and I have updated this PR to mention that the issue is fixed in HW 1.6.3+.

**Comment by seviet** [comment]
@JacobLNewton Would you merge if it looks good to you

**Pull request merged**
